Fri May 05 14:26:28 CEST 2017 : Apache Derby Network Server - 10.11.1.2 - (1629631) démarré et prêt à accepter les connexions sur le port 1527
----------------------------------------------------------------
Fri May 05 14:26:28 CEST 2017:
Amorçage de Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631) : instance a816c00e-015b-d893-5dbc-ffffd45fdef9 
dans le répertoire de base de données C:\Users\martin\Desktop\Dossier\INSA\DASI\DASI_PART_2\gustatif avec le chargeur de classe sun.misc.Launcher$AppClassLoader@6f94fa3e
Chargé de file:/C:/Program%20Files/Java/jdk1.8.0_111/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Program Files\Java\jdk1.8.0_111\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\martin\Desktop\Dossier\INSA\DASI\DASI_PART_2
Chargeur de classe de la base de données démarré - derby.database.classpath = ''
Fri May 05 14:26:29 CEST 2017 Thread[DRDAConnThread_2,5,main] (XID = 2689), (SESSIONID = 0), (DATABASE = gustatif), (DRDAID = {1}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Echec de l'authentification de la connexion. Cause : Authentification non valide..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Echec de l'authentification de la connexion. Cause : Authentification non valide..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR 08004: Echec de l'authentification de la connexion. Cause : Authentification non valide..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Fri May 05 14:26:29 CEST 2017 Thread[DRDAConnThread_2,5,main] (DATABASE = gustatif), (DRDAID = {1}), Echec de l'authentification de la connexion. Cause : Authentification non valide..
----------------------------------------------------------------
Fri May 05 14:27:24 CEST 2017:
Amorçage de Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631) : instance 601a400f-015b-d893-5dbc-ffffd45fdef9 
dans le répertoire de base de données C:\Users\martin\Desktop\Dossier\INSA\DASI\DASI_PART_2\gustatif-DB avec le chargeur de classe sun.misc.Launcher$AppClassLoader@6f94fa3e
Chargé de file:/C:/Program%20Files/Java/jdk1.8.0_111/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Program Files\Java\jdk1.8.0_111\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\martin\Desktop\Dossier\INSA\DASI\DASI_PART_2
Chargeur de classe de la base de données démarré - derby.database.classpath = ''
----------------------------------------------------------------
Fri May 05 14:27:33 CEST 2017:
Fermeture de l'instance 601a400f-015b-d893-5dbc-ffffd45fdef9 sur le répertoire de base de données C:\Users\martin\Desktop\Dossier\INSA\DASI\DASI_PART_2\gustatif-DB avec le chargeur de classe sun.misc.Launcher$AppClassLoader@6f94fa3e 
Fri May 05 14:27:33 CEST 2017 Thread[DRDAConnThread_2,5,main] (DATABASE = gustatif-DB), (DRDAID = {3}), Arrêt de la base de données 'gustatif-DB'.
----------------------------------------------------------------
Fri May 05 14:28:04 CEST 2017:
Amorçage de Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631) : instance ce8780ad-015b-d893-5dbc-ffffd45fdef9 
dans le répertoire de base de données C:\Users\martin\Desktop\Dossier\INSA\DASI\DASI_PART_2\gustatif-DB avec le chargeur de classe sun.misc.Launcher$AppClassLoader@6f94fa3e
Chargé de file:/C:/Program%20Files/Java/jdk1.8.0_111/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_111-b14
user.dir=C:\Program Files\Java\jdk1.8.0_111\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\martin\Desktop\Dossier\INSA\DASI\DASI_PART_2
Chargeur de classe de la base de données démarré - derby.database.classpath = ''
